-- Q1. What is total revenue generated by male vs female customers.
SELECT gender, SUM(purchase_amount)
FROM customer
group by gender 

--Q2. Which customers used a discount but still spent more than the average purchase amount.
SELECT customer_id , purchase_amount
FROM customer
where discount_applied='Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) from customer)


-- Q3. which are the top 5 products with highest average review rating
SELECT item_purchased,
       ROUND(AVG(review_rating)::numeric, 2) AS "Average Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average purchase amount between Standard and Express shipping.
SELECT shipping_type , round(AVG(purchase_amount)::numeric , 2)
FROM customer
WHERE shipping_type in ('Express' ,'Standard')
GROUP BY shipping_type


--Q5. Do subscribed customers spend more ? compare average spend and total revenue between subs and non-subs
SELECT subscription_status,
COUNT(customer_id) as Total_customers,
Round(AVG(purchase_amount)::numeric , 2) as Average_Spend,
Round(SUM(purchase_amount)::numeric , 2) as Total_Revenue
From customer
GROUP BY subscription_status
order by Average_spend , Total_revenue Desc;

--Q6. which 5 products have the highest percentage of purchases with discounts applied.
SELECT item_purchased , 
ROUND (AVG (CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0 END)*100 , 2
) AS discount_rate
FROM CUSTOMER
GROUP BY item_purchased
order BY discount_rate Desc
Limit 5;

--Q7. Segment the customers into new , Returning and loyal based on their total number of previous purchases
-- and show the count of each segment 
with customer_type as (
SELECT previous_purchases , customer_id,
CASE 
WHEN previous_purchases IN (1,2) THEN 'New'
WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)
SELECT customer_segment , COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment

--Q8. what are the top 3 most purchased products within each category?
SELECT  category,item_purchased,total_purchases
FROM (
    SELECT  category,item_purchased,
        SUM(previous_purchases) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY SUM(previous_purchases) DESC
        ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE rank_in_category <= 3;


-- Q9. Are customers who are repeat buyers(purchase of more than 5) likely to subscribe?
SELECT subscription_status,
COUNT (customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases >5
GROUP BY subscription_status


-- Q10.what is the revenue contributio of each age group 
SELECT SUM(previous_purchases) as revenue_contribution , age_group
FROM customer
GROUP BY age_group
order by revenue_contribution desc




















